# Generated by Django 5.0.6 on 2024-10-27 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='empleado',
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('Tipos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaWeb.tipos')),
            ],
        ),
        migrations.AddField(
            model_name='caja',
            name='Usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.usuarios'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.usuarios'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
