# Generated by Django 5.1 on 2024-11-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0002_tipos_remove_venta_cliente_remove_venta_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Tipos',
            new_name='tipos',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaWeb.categoria'),
        ),
        migrations.CreateModel(
            name='TallexCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaWeb.categoria')),
                ('talle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SistemaWeb.talle')),
            ],
        ),
    ]
