# Generated by Django 5.1 on 2024-11-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0003_categoria_talle_rename_tipos_usuarios_tipos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.proveedor')),
            ],
        ),
    ]
